version: "3.8"

services:
  clinica-odont:
    build: .
    container_name: clinica-odontologica
    ports:
      - "8086:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - n8n

networks:
  n8n:
    driver: bridge
